name: ci-build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build build Docker images
      run: docker build -t docker-splunk-appinspect:latest .
    - name: Build build Docker images
      run: docker run --rm -t docker-splunk-appinspect:latest